---
# tasks file for artifactory

- name: install java 11
  ansible.builtin.apt:
    name: openjdk-11-jdk
    state: present

- name: install java 11
  ansible.builtin.apt:
    name: 
      - wget
      - unzip
    state: present

- name: Configuring java path
  ansible.builtin.template:
    src: templates/bash-profile.j2
    dest: /etc/profile
  

#- name: reload the /etc/profile
#  ansible.builtin.command: source  /etc/profile
#  register: myoutput
# executable: /bin/sh


- name: add the repository key to repos list
  ansible.builtin.get_url:
    url:  https://releases.jfrog.io/artifactory/bintray-artifactory/org/artifactory/oss/jfrog-artifactory-oss/7.31.11/jfrog-artifactory-oss-7.31.11-linux.tar.gz
    dest: /home/ubuntu/jfrog-artifactory-oss-7.31.11-linux.tar.gz
    mode: '0755'
 
- name: Copy the downloaded file to the etc repo
  ansible.builtin.copy:
    src: /home/ubuntu/jfrog-artifactory-oss-7.31.11-linux.tar.gz
    dest: /etc/apt/sources.list.d/jfrog-artifactory-oss-7.31.11-linux.tar.gz
    remote_src: yes
    follow: yes

- name: update cache
  ansible.builtin.apt:
    update_cache: yes

- name: install artifactory
  ansible.builtin.apt:
    name: jfrog-artifactory-oss-7.31.11-linux.tar.gz
    state: present

- name: start and enable artifactory
  ansible.builtin.service:
    name: artifactory
    state: started
    enabled: yes
